---
title: "Mi primer blog"
date: 2019-01-08
---
title: Mi primer blog
author: Alfonso
email: lolopezalfonso@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Este es mi primer blog en github

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
